[mypy]
python_version = 3.12
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
disallow_incomplete_defs = False
check_untyped_defs = True
disallow_untyped_decorators = False
no_implicit_optional = True
strict_optional = True

# Ignore missing imports for external libraries
[mypy.plugins.wx.*]
ignore_missing_imports = True

[mypy.plugins.geopy.*]
ignore_missing_imports = True

[mypy-wx.*]
ignore_missing_imports = True

[mypy-geopy.*]
ignore_missing_imports = True
