blank_issues_enabled: true
contact_links:
  - name: AccessiWeather Documentation
    url: https://github.com/Orinks/AccessiWeather/tree/main/docs
    about: Check the documentation before opening an issue
