#!/usr/bin/env python3
"""
Generate _version.py from pyproject.toml for PyInstaller builds.

This script reads the version from pyproject.toml and writes it to
src/accessiweather/_version.py, ensuring the version is available
at runtime even in PyInstaller bundles where importlib.metadata
and pyproject.toml are not accessible.

Usage:
    python scripts/generate_version.py
"""

import sys
from pathlib import Path

import tomllib


def main() -> int:
    """Generate _version.py from pyproject.toml."""
    project_root = Path(__file__).resolve().parents[1]
    pyproject_path = project_root / "pyproject.toml"
    version_path = project_root / "src" / "accessiweather" / "_version.py"

    if not pyproject_path.exists():
        print(f"Error: {pyproject_path} not found", file=sys.stderr)
        return 1

    with pyproject_path.open("rb") as f:
        data = tomllib.load(f)

    version = data.get("project", {}).get("version")
    if not version:
        print("Error: Could not find project.version in pyproject.toml", file=sys.stderr)
        return 1

    content = f'''"""Auto-generated version file. Do not edit manually.

Generated by scripts/generate_version.py from pyproject.toml.
"""

__version__ = "{version}"
'''

    version_path.write_text(content)
    print(f"Generated {version_path} with version {version}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
