#!/usr/bin/env python3
"""
Generate _build_info.py with build metadata for PyInstaller builds.

This script creates src/accessiweather/_build_info.py with build-time
information like the nightly tag, ensuring the app knows whether it's
a nightly build and can properly compare versions for updates.

Usage:
    python scripts/generate_build_info.py                    # Stable build (BUILD_TAG = None)
    python scripts/generate_build_info.py nightly-20260201   # Nightly build
"""

import sys
from pathlib import Path


def main() -> int:
    """Generate _build_info.py with build metadata."""
    project_root = Path(__file__).resolve().parents[1]
    build_info_path = project_root / "src" / "accessiweather" / "_build_info.py"

    # Get build tag from command line (None for stable builds)
    build_tag = sys.argv[1] if len(sys.argv) > 1 else None
    tag_value = f'"{build_tag}"' if build_tag else "None"

    content = f'''"""Auto-generated build info. Do not edit manually.

Generated by scripts/generate_build_info.py at build time.
"""

# Build tag for nightly builds (e.g., "nightly-20260201"), None for stable
BUILD_TAG: str | None = {tag_value}
'''

    build_info_path.write_text(content)
    print(f"Generated {build_info_path} with BUILD_TAG = {tag_value}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
