"""Dialog for configuring AccessiWeather settings.

This module provides backward compatibility by re-exporting the SettingsDialog
from the new modular settings package.
"""

# Re-export the SettingsDialog for backward compatibility
from .settings import SettingsDialog

# Re-export constants for backward compatibility
from .settings.constants import (
    ALERT_RADIUS_KEY,
    API_KEYS_SECTION,
    AUTO_REFRESH_NATIONAL_KEY,
    AUTO_UPDATE_CHECK_KEY,
    CACHE_ENABLED_KEY,
    CACHE_TTL_KEY,
    DATA_SOURCE_AUTO,
    DATA_SOURCE_KEY,
    DATA_SOURCE_NWS,
    DATA_SOURCE_OPENMETEO,
    DEFAULT_AUTO_UPDATE_CHECK,
    DEFAULT_DATA_SOURCE,
    DEFAULT_TEMPERATURE_UNIT,
    DEFAULT_UPDATE_CHANNEL,
    DEFAULT_UPDATE_CHECK_INTERVAL,
    MINIMIZE_ON_STARTUP_KEY,
    MINIMIZE_TO_TRAY_KEY,
    PRECISE_LOCATION_ALERTS_KEY,
    SHOW_NATIONWIDE_KEY,
    TASKBAR_ICON_DYNAMIC_ENABLED_KEY,
    TASKBAR_ICON_TEXT_ENABLED_KEY,
    TASKBAR_ICON_TEXT_FORMAT_KEY,
    TEMPERATURE_UNIT_KEY,
    UPDATE_CHANNEL_KEY,
    UPDATE_CHECK_INTERVAL_KEY,
    UPDATE_INTERVAL_KEY,
    VALID_DATA_SOURCES,
)

# Export all for backward compatibility
__all__ = [
    "SettingsDialog",
    "ALERT_RADIUS_KEY",
    "API_KEYS_SECTION",
    "AUTO_REFRESH_NATIONAL_KEY",
    "AUTO_UPDATE_CHECK_KEY",
    "CACHE_ENABLED_KEY",
    "CACHE_TTL_KEY",
    "DATA_SOURCE_AUTO",
    "DATA_SOURCE_KEY",
    "DATA_SOURCE_NWS",
    "DATA_SOURCE_OPENMETEO",
    "DEFAULT_AUTO_UPDATE_CHECK",
    "DEFAULT_DATA_SOURCE",
    "DEFAULT_TEMPERATURE_UNIT",
    "DEFAULT_UPDATE_CHANNEL",
    "DEFAULT_UPDATE_CHECK_INTERVAL",
    "MINIMIZE_ON_STARTUP_KEY",
    "MINIMIZE_TO_TRAY_KEY",
    "PRECISE_LOCATION_ALERTS_KEY",
    "SHOW_NATIONWIDE_KEY",
    "TASKBAR_ICON_DYNAMIC_ENABLED_KEY",
    "TASKBAR_ICON_TEXT_ENABLED_KEY",
    "TASKBAR_ICON_TEXT_FORMAT_KEY",
    "TEMPERATURE_UNIT_KEY",
    "UPDATE_CHANNEL_KEY",
    "UPDATE_CHECK_INTERVAL_KEY",
    "UPDATE_INTERVAL_KEY",
    "VALID_DATA_SOURCES",
]
