# GitHub Pages configuration for AccessiWeather
title: AccessiWeather Downloads
description: Download the latest AccessiWeather builds - An accessible weather application with screen reader support

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Include files that start with underscores
include:
  - _headers

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Site settings
url: "https://orinks.github.io"
baseurl: "/AccessiWeather"

# Navigation
header_pages:
  - index.html
  - download-links.md
  - user_manual.md

# Social links
github_username: Orinks
repository: Orinks/AccessiWeather

# SEO settings
author: Orinks
twitter:
  username:
  card: summary

# Accessibility settings
lang: en-US
