name: Dev Briefcase Sanity

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

env:
  PYTHON_VERSION: "3.12"

jobs:
  make-status:
    name: Run installer/make.py (no arguments)
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e .[dev]
          pip install briefcase


      - name: Create Briefcase scaffold
        run: |
          echo "Creating Briefcase app scaffold..."
          python installer/make.py create --platform windows
        env:
          DISPLAY: ""
          ACCESSIWEATHER_TEST_MODE: "1"

      - name: Build Briefcase app
        run: |
          echo "Building Briefcase app..."
          python installer/make.py build --platform windows
        env:
          DISPLAY: ""
          ACCESSIWEATHER_TEST_MODE: "1"

      - name: Create portable ZIP
        run: |
          echo "Creating portable ZIP..."
          python installer/make.py zip --platform windows
        env:
          DISPLAY: ""
          ACCESSIWEATHER_TEST_MODE: "1"

      - name: Package MSI installer
        run: |
          echo "Packaging MSI installer..."
          python installer/make.py package --platform windows
        env:
          DISPLAY: ""
          ACCESSIWEATHER_TEST_MODE: "1"

      - name: Verify outputs
        run: |
          echo "Verifying build artifacts..."
          set -e
          MSI_PATH=$(find dist -name "*.msi" | head -1)
          ZIP_PATH=$(find dist -name "AccessiWeather_Portable_v*.zip" | head -1)
          if [ -z "$MSI_PATH" ] || [ ! -f "$MSI_PATH" ]; then
            echo "✗ Missing MSI in dist/"
            exit 1
          fi
          if [ -z "$ZIP_PATH" ] || [ ! -f "$ZIP_PATH" ]; then
            echo "✗ Missing portable ZIP in dist/"
            exit 1
          fi
          echo "✓ Found MSI: $MSI_PATH"
          echo "✓ Found ZIP: $ZIP_PATH"
