name: Experimental wxPython Tests

on:
  push:
    branches: [ experimental-wx-debug ]
  pull_request:
    branches: [ experimental-wx-debug ]
  workflow_dispatch:

jobs:
  test-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-mock pytest-cov flake8 mypy isort black
        pip install -e .
        pip install wxPython==4.2.2
        
    - name: Run experimental wxPython tests
      run: |
        # Run tests with our custom test runner
        python run_wx_tests.py tests/test_wx_debug.py -v --memory-tracking
      env:
        ACCESSIWEATHER_TESTING: "1"
        ACCESSIWEATHER_SKIP_API_CALLS: "1"
        PYTHONPATH: ${{ github.workspace }}
        PYTHONFAULTHANDLER: "1"
        
    - name: Run isolated tests
      run: |
        # Run tests in isolated mode
        python run_wx_tests.py tests/test_wx_debug.py -v --isolated
      env:
        ACCESSIWEATHER_TESTING: "1"
        ACCESSIWEATHER_SKIP_API_CALLS: "1"
        PYTHONPATH: ${{ github.workspace }}
        PYTHONFAULTHANDLER: "1"
        
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-logs
        path: tests/logs/
        if-no-files-found: ignore

  test-ubuntu:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-mock pytest-cov flake8 mypy isort black
        pip install -e .
        
    - name: Install wxPython and required libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libnotify-dev libsdl2-2.0-0 libtiff5-dev libjpeg-dev
        pip install -U wxPython==4.2.2
        
    - name: Run experimental wxPython tests
      run: |
        # Run tests with our custom test runner
        python run_wx_tests.py tests/test_wx_debug.py -v --memory-tracking
      env:
        ACCESSIWEATHER_TESTING: "1"
        ACCESSIWEATHER_SKIP_API_CALLS: "1"
        PYTHONPATH: ${{ github.workspace }}
        PYTHONFAULTHANDLER: "1"
        
    - name: Run isolated tests
      run: |
        # Run tests in isolated mode
        python run_wx_tests.py tests/test_wx_debug.py -v --isolated
      env:
        ACCESSIWEATHER_TESTING: "1"
        ACCESSIWEATHER_SKIP_API_CALLS: "1"
        PYTHONPATH: ${{ github.workspace }}
        PYTHONFAULTHANDLER: "1"
        
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-logs-ubuntu
        path: tests/logs/
        if-no-files-found: ignore
