name: AccessiWeather CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99.0'
      PYTHONPATH: ${{ github.workspace }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set up virtual framebuffer
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libgtk-3-dev
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -e .

    - name: Run tests with pytest
      run: |
        pytest --cov=accessiweather tests/ --cov-report=xml -v

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
