name: Python Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ['3.12']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-mock
        pip install -e .
        
    - name: Install wxPython on Windows
      if: matrix.os == 'windows-latest'
      run: |
        pip install -U wxPython==4.2.2
        
    - name: Install wxPython on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev
        pip install -U wxPython==4.2.2
        
    - name: Run tests
      run: |
        python -m pytest tests/test_location_switching_fixed.py tests/test_notification_settings.py
