name: AccessiWeather CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99.0'
      PYTHONPATH: ${{ github.workspace }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set up virtual framebuffer
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          xvfb \
          build-essential \
          libgtk-3-dev \
          libwebkitgtk-6.0-dev \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libnotify-dev \
          libsdl2-dev
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pytest-wx
        # Install wxPython separately first to isolate potential issues
        pip install wxPython
        pip install -e .

    - name: Run tests with pytest
      run: |
        pytest --cov=accessiweather tests/ --cov-report=xml -v

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
