name: AccessiWeather CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99.0'
      PYTHONPATH: ${{ github.workspace }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Set up virtual framebuffer
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          xvfb \
          build-essential \
          libgtk-3-dev \
          libwebkitgtk-6.0-dev \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libnotify-dev \
          libsdl2-dev \
          libjpeg-dev \
          libpng-dev \
          libtiff-dev \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          freeglut3-dev
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

    - name: Install system dependencies for libtiff
      run: |
        sudo apt-get update
        sudo apt-get install -y libtiff-dev

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pip setuptools wheel
        echo "Installing test dependencies..."
        pip install pytest pytest-cov pytest-mock
        echo "Installing wxPython (forcing binary from extras URL)..."
        pip install \
          -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-24.04/ \
          wxPython --only-binary :all: -vvv
        echo "Installing other project dependencies..."
        pip install requests geopy python-dateutil plyer
        echo "Installing AccessiWeather in editable mode (no deps)..."
        pip install -e . --no-build-isolation --no-deps

    - name: Run tests with pytest
      run: |
        pytest --cov=accessiweather tests/ --cov-report=xml -v

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
