name: Python Tests Ubuntu

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-mock flake8 mypy isort black
        pip install -e .
        
    - name: Install wxPython and required libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libnotify-dev libsdl2-2.0-0 libtiff5-dev libjpeg-dev
        pip install -U wxPython==4.2.2
        
    - name: Run black
      run: |
        python -m black --check src/accessiweather tests || echo "Black check failed but continuing"
        
    - name: Run isort
      run: |
        python -m isort --check-only --diff src/accessiweather tests || echo "isort check failed but continuing"
        
    - name: Run flake8
      run: |
        python -m flake8 src/accessiweather tests || echo "flake8 check failed but continuing"
        
    - name: Run mypy
      run: |
        python -m mypy src/accessiweather || echo "mypy check failed but continuing"
        
    - name: Run tests
      run: |
        python -m pytest tests/test_location_switching_fixed.py tests/test_notification_settings.py || echo "Tests failed but continuing"
