name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

defaults:
  run:
    shell: bash

env:
  FORCE_COLOR: "1"

jobs:
  test:
    name: Lint and Test (Windows)
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', 'pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install -e .

    - name: Headless make.py smoke check
      env:
        ACCESSIWEATHER_TEST_MODE: "1"
      run: |
        python installer/make.py

    - name: Ruff format check
      run: ruff format --check .

    - name: Ruff lint
      run: ruff check .

    - name: Run tests
      env:
        PYTHONPATH: src
        PYTEST_DISABLE_PLUGIN_AUTOLOAD: 1
        ACCESSIWEATHER_TEST_MODE: "1"
      run: |
        pytest -v -p pytest_asyncio --tb=short --maxfail=1

    - name: CI Summary
      if: always()
      run: |
        echo "=== CI Workflow Summary ==="
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
        echo "Event: ${{ github.event_name }}"
        if [ "${{ job.status }}" = "success" ]; then
          echo "✅ All checks passed!"
        else
          echo "❌ Some checks failed"
        fi
